# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7_6t_gFBkwEavGg-NFOCnuCyBkZBq2j
"""

!pip install gradio yfinance prophet textblob

import gradio as gr
import yfinance as yf
import pandas as pd
from prophet import Prophet
import matplotlib.pyplot as plt
import datetime
from textblob import TextBlob
import urllib.request
import xml.etree.ElementTree as ET

# 1. دالة سحب الأخبار من الـ RSS
def get_yahoo_news(ticker):
    news_titles = []
    url = f"https://feeds.finance.yahoo.com/rss/2.0/headline?s={ticker}&region=US&lang=en-US"
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response:
            xml_data = response.read()
            root = ET.fromstring(xml_data)
            for item in root.findall('./channel/item')[:5]:
                title = item.find('title').text
                news_titles.append(title)
    except Exception as e:
        print("Error fetching news:", e)
    return news_titles

# 2. الدالة الشاملة للتحليل (نفس الدالة السابقة بدون تغيير)
def analyze_stock(ticker, days):
    try:
        stock_data = yf.download(ticker, period="5y")
        if stock_data.empty:
            return None, "❌ لم يتم العثور على بيانات لهذا السهم.", "لا يوجد أخبار"

        if isinstance(stock_data.columns, pd.MultiIndex):
            stock_data.columns = stock_data.columns.get_level_values(0)

        hist = stock_data[['Close']].copy()
        hist.dropna(inplace=True)

        hist['MA50'] = hist['Close'].rolling(window=50).mean()
        hist['MA200'] = hist['Close'].rolling(window=200).mean()

        df = hist.reset_index().copy()
        df.rename(columns={'Date': 'ds', 'Close': 'y'}, inplace=True)
        df['ds'] = pd.to_datetime(df['ds']).apply(lambda x: x.replace(tzinfo=None))

        model = Prophet(daily_seasonality=True)
        model.fit(df[-1000:])

        future = model.make_future_dataframe(periods=int(days))
        forecast = model.predict(future)

        current_price = float(hist['Close'].iloc[-1])
        predicted_price = float(forecast['yhat'].iloc[-1])
        price_diff = ((predicted_price - current_price) / current_price) * 100

        if price_diff > 5:
            decision = f"🟢 شراء (Buy) - متوقع زيادة بنسبة {price_diff:.1f}%"
        elif price_diff < -5:
            decision = f"🔴 بيع (Sell) - متوقع هبوط بنسبة {abs(price_diff):.1f}%"
        else:
            decision = f"🟡 احتفاظ (Hold) - السعر مستقر نسبياً التغيير {price_diff:.1f}%"

        news_summary = ""
        sentiment_status = "محايدة ➖"
        news_list = get_yahoo_news(ticker)
        sentiment_score = 0
        news_count = len(news_list)

        if news_count > 0:
            for title in news_list:
                blob = TextBlob(title)
                sentiment_score += blob.sentiment.polarity
                news_summary += f"🔸 {title}\n\n"

            avg_sentiment = sentiment_score / news_count
            if avg_sentiment > 0.05:
                sentiment_status = "إيجابية 📈 (الأخبار تدعم السهم)"
            elif avg_sentiment < -0.05:
                sentiment_status = "سلبية 📉 (الأخبار تحذر من السهم)"
        else:
            news_summary = "⚠️ لم يتم العثور على أخبار حديثة."

        fig, ax = plt.subplots(figsize=(10, 5))
        recent_hist = hist[-365:]
        recent_dates = recent_hist.index.tz_localize(None) if recent_hist.index.tz is not None else recent_hist.index

        ax.plot(recent_dates, recent_hist['Close'], label='Actual Price', color='#2c3e50', linewidth=2)
        ax.plot(recent_dates, recent_hist['MA50'], label='MA50', color='#2980b9', alpha=0.7, linestyle='-.')
        ax.plot(recent_dates, recent_hist['MA200'], label='MA200', color='#c0392b', alpha=0.7, linestyle='-.')

        future_dates = forecast['ds'].iloc[-int(days):]
        future_yhat = forecast['yhat'].iloc[-int(days):]
        ax.plot(future_dates, future_yhat, label='Prophet Forecast', color='#27ae60', linestyle='dashed', linewidth=2.5)

        ax.set_title(f"Stock Analysis for {ticker.upper()}", fontsize=14, fontweight='bold')
        ax.set_xlabel("Date")
        ax.set_ylabel("Price (USD)")
        ax.legend()
        ax.grid(True, alpha=0.3)
        fig.tight_layout()

        analysis_text = f"""
        ### 📊 ملخص التحليل الذكي:
        * **السعر الحالي:** `{current_price:.2f}$`
        * **السعر المتوقع:** `{predicted_price:.2f}$`

        ### 🤖 توصيات الموديل:
        * **القرار المالي:** {decision}
        * **تحليل المشاعر (NLP):** {sentiment_status}
        """
        return fig, analysis_text, news_summary
    except Exception as e:
        return None, f"❌ حدث خطأ: {str(e)}", "حاول مرة أخرى."

# 3. واجهة المستخدم الجديدة (UI/UX)
# استخدام ثيم احترافي
custom_theme = gr.themes.Default(primary_hue="blue", secondary_hue="slate")

with gr.Blocks(theme=custom_theme, title="AI Stock Predictor") as interface:
    # عنوان الصفحة وتنسيقه بـ HTML
    gr.HTML("""
    <div style="text-align: center; padding: 20px;">
        <h1 style="color: #2c3e50; font-family: Arial, sans-serif;">📈 المحلل المالي الذكي (AI Stock Predictor)</h1>
        <p style="color: #7f8c8d; font-size: 16px;">مشروع متكامل يدمج بين توقعات السلاسل الزمنية وتحليل اللغات الطبيعية للأخبار</p>
    </div>
    """)

    # قائمة تعليمات قابلة للطي
    with gr.Accordion("ℹ️ كيفية استخدام التطبيق (اضغط للتوسيع)", open=False):
        gr.Markdown("""
        1. **رمز السهم:** أدخل رمز الشركة في البورصة (مثال: `AAPL` لآبل، `META` لفيسبوك، `GOOG` لجوجل).
        2. **فترة التوقع:** استخدم الشريط المنزلق لتحديد عدد الأيام المستقبلية التي تريد توقعها.
        3. اضغط على **"تحليل وتوقع السعر"** وانتظر بضع ثوانٍ لرؤية النتائج.
        """)

    with gr.Row():
        # العمود الأيمن: أدوات الإدخال
        with gr.Column(scale=1):
            gr.Markdown("### ⚙️ إعدادات التحليل")
            ticker_input = gr.Textbox(label="رمز السهم (Ticker)", value="AAPL", placeholder="اكتب الرمز هنا...")
            days_input = gr.Slider(minimum=7, maximum=90, value=30, step=1, label="فترة التوقع (أيام)")
            analyze_btn = gr.Button("تحليل وتوقع السعر 🚀", variant="primary", size="lg")

        # العمود الأيسر: عرض النتائج في تبويبات (Tabs)
        with gr.Column(scale=3):
            with gr.Tabs():
                # التبويب الأول: الرسم والملخص
                with gr.Tab("الرسم البياني والتوصيات 📊"):
                    report_output = gr.Markdown(label="التقرير المالي")
                    plot_output = gr.Plot(label="الرسم البياني")

                # التبويب الثاني: الأخبار
                with gr.Tab("تحليل الأخبار والمشاعر 📰"):
                    gr.Markdown("أحدث 5 عناوين أخبار متعلقة بالسهم تم جلبها وتحليلها باستخدام `TextBlob`:")
                    news_output = gr.Textbox(label="عناوين الأخبار", lines=10, interactive=False)

    # تشغيل الدالة عند الضغط على الزر
    analyze_btn.click(fn=analyze_stock, inputs=[ticker_input, days_input], outputs=[plot_output, report_output, news_output])

# تشغيل التطبيق
interface.launch(share=True, debug=True)